# Generated by Django 3.0.3 on 2020-06-26 11:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemaperson',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='cinemaprofession',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['film__title']},
        ),
        migrations.AlterField(
            model_name='cinemafilmpersonprofession',
            name='cinema_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.CinemaPerson'),
        ),
        migrations.AlterField(
            model_name='cinemafilmpersonprofession',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.Film'),
        ),
        migrations.AlterField(
            model_name='cinemafilmpersonprofession',
            name='profession',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='cinema.CinemaProfession'),
        ),
        migrations.AlterField(
            model_name='cinemaperson',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cinema.Country'),
        ),
        migrations.AlterField(
            model_name='cinemaperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema.ImdbRating'),
        ),
        migrations.AlterField(
            model_name='film',
            name='mpaa_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cinema.MpaaRating'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='film',
            name='usa_gross',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='world_gross',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Invalid genre name format.', regex='^[A-Z][a-z]+[-]?[a-z]+$')]),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Invalid language name format.', regex='^[A-Z][a-z]+$')]),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_author',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, error_messages={'min_value': 'Product price cannot be less than 0.99.'}, max_digits=5, validators=[django.core.validators.MinValueValidator(0.99)]),
        ),
    ]
