# Generated by Django 3.0.8 on 2020-07-23 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20200626_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemafilmpersonprofession',
            options={'ordering': ['film__title', 'profession', 'cinema_person__user__first_name'], 'verbose_name': 'Cinema film person profession', 'verbose_name_plural': 'Cinema films persons professions'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.CreateModel(
            name='CommentToProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Display on screen?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Product')),
            ],
            options={
                'verbose_name_plural': 'Comments to products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentToPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Display on screen?')),
                ('cinema_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.CinemaPerson')),
            ],
            options={
                'verbose_name_plural': 'Comments to persons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentToNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Display on screen?')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.News')),
            ],
            options={
                'verbose_name_plural': 'Comments to news',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentToFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('author', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Display on screen?')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.Film')),
            ],
            options={
                'verbose_name_plural': 'Comments to films',
                'ordering': ['-created_at'],
            },
        ),
    ]
